### ISSUE TITLE
Unterschiedliche htaccess pro Instanz

### ISSUE THREAD

**Issue by denniserdmann** [nutshell-framework/deployer-recipes#1]
z.B. `.htaccess.stage`, `.htaccess.prod`

**Comment by richardhj** [comment]
Done in 83113e4e8e45b83ca7c3a8ae0ed98e8e5e48c826.

**Comment by denniserdmann** [comment]
Habe es im aktuellen Projekt WM getestet, es funktioniert allerdings noch nicht. Ich habe auch geprüft, ob ich die normale `.htaccess` per exclude ausschließen muss, aber das ändert nichts.

**Comment by denniserdmann** [comment]
Mein Fehler. Ich hatte das abweichende `public-dir` in der composer.json nicht festgelegt.
